[WIP] Rewrite docs to inlude examples
vercel/micro pull request #115
Opened 2016-12-27 12:49 UTC by timneutkens

I rewrote / moved a lot of stuff around. Please have a look :) Will add the examples soon.

2017-01-02 13:59 UTC, leo requested changes

2017-01-02 13:59 UTC, leo commented on README.md
> +## How to use
> Usage

2017-01-02 13:59 UTC, leo commented on README.md
> +npm install micro --save
Command line indicator (dollar sign) missing. Also please put the flag before the package name!

2017-01-02 13:59 UTC, leo commented on README.md
> +Add a script to your package.json like this:
`package.json`, not package.json

2017-01-02 21:19 UTC, timneutkens commented on README.md
> +Add a script to your package.json like this:
Done 🔥

2017-01-02 21:19 UTC, timneutkens commented on README.md
> +npm install micro --save
Done 🔥

2017-01-02 21:19 UTC, timneutkens commented on README.md
> +## How to use
Done 🔥

2017-01-09 22:52 UTC, NetOperatorWibby commented
Oh wow, thanks for this PR! I learned a lot by looking at the revised README.

2017-01-20 14:24 UTC, onbjerg commented on README.md
> +{
Missing opening code block (```)

2017-01-20 14:24 UTC, onbjerg commented on README.md
> +#### Api
API (it's an abbreviation)

2017-01-20 14:24 UTC, onbjerg commented on README.md
> +#### Api
API (it's an abbreviation)

2017-01-20 14:24 UTC, onbjerg commented on README.md
> +#### Api
API (it's an abbreviation)

2017-01-20 14:24 UTC, onbjerg commented on README.md
> +#### Api
API (it's an abbreviation)

2017-01-20 14:24 UTC, onbjerg commented
Added some comments, hope you don't mind 😊

2017-01-25 20:02 UTC, timneutkens commented on README.md
> +{
Fixed 🙌

2017-01-25 20:02 UTC, timneutkens commented on README.md
> +#### Api
Fixed 🙌

2017-01-25 20:02 UTC, timneutkens commented on README.md
> +#### Api
Fixed 🙌

2017-01-25 20:02 UTC, timneutkens commented on README.md
> +#### Api
Fixed 🙌

2017-01-25 20:02 UTC, timneutkens commented on README.md
> +#### Api
Fixed 🙌

2017-01-25 21:18 UTC, timneutkens commented
@leo @rauchg can you do a final review?

2017-01-25 21:21 UTC, timneutkens commented
I wonder if we should disable `xo` for the examples 🤔

2017-02-04 20:56 UTC, merged

2017-02-04 20:56 UTC, leo commented
@timneutkens 😍