Support handling query strings
vercel/micro pull request #203
Opened 2017-03-25 01:03 UTC by malexdev

2017-03-25 06:16 UTC, floatdrop requested changes

2017-03-25 06:16 UTC, floatdrop commented on test/index.js
> +  t.deepEqual(res, 'test')
You can just call `t.deepEqual` in req handler.

2017-03-25 06:16 UTC, floatdrop commented on test/index.js
> +  t.deepEqual(res, JSON.stringify({a: 'a', b: 'b', c: 'c'}))
Here too – `JSON.stringify` is not good approach.

2017-03-25 06:16 UTC, floatdrop commented on lib/server.js
> +exports.query = req => Promise.resolve().then(() => {
There is no need for `Promise` here – no async work is done.

2017-03-25 14:42 UTC, malexdev commented on lib/server.js
> +exports.query = req => Promise.resolve().then(() => {
Gotcha. Thought we might want to keep it the same as the `.json` API so made it use the promise. Makes sense to make it sync though.

2017-03-25 14:48 UTC, floatdrop requested changes

2017-03-25 14:48 UTC, floatdrop commented on test/index.js
> +    t.deepEqual(q, qs)
With latest fix (7.2.2) – you need to return here something, otherwise request will hang.

2017-03-25 14:48 UTC, floatdrop commented on test/index.js
> +    t.deepEqual(q, qs)
And here too.

2017-03-25 19:19 UTC, floatdrop reviewed
`url.parse` is not quite get things right – maybe it is better to use [`query-string`](https://github.com/sindresorhus/query-string) module or look at [URL class](https://nodejs.org/api/url.html#url_the_whatwg_url_api). Anyways parsing query string is trivial task, should it have own helper?

2017-03-26 02:11 UTC, malexdev commented
If you don't think it would be a good fit for micro that's fine, I just thought it'd be helpful to have built in.

Also, what is it that `url.parse` doesn't get right? I haven't seen any issues with it so far.

2017-03-26 08:34 UTC, floatdrop commented
@malexdev standart module does not support arrays in query or nested objects for example:

```js
url.parse('http://google.com/?query=1&a[0]=1&a[1]=1', true).query
// { query: '1', 'a[0]': '1', 'a[1]': '1' }
```

I can not merge or reject PR, just judging by #174/#184.

2017-03-27 13:21 UTC, leo commented
Thank you for your effort, guys! But this is not something we'd like to see built-in. The point of `micro` is to only provide very little (the most important) abstractions for microservices.

2017-03-27 13:21 UTC, closed without merging